---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore, Dockerfile, fig.yml]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
kramdown:
  hard_wrap: false

baseurl: /nicknack

highlighter: pygments


### content configuration ###
title:       "Nick Nack: mrjob extras"
keywords:    "mrjob, hadoop, multiple output"
description: "A library of mrjob extras to make hadoop do what you want"
source_link: "https://github.com/empiricalresults/nicknack"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  section1:  '#230903'
  section2:  '#656256'
  section3:  '#9EBC9F'
  section4:  '#F4F2F3'
  
